Created a react-rails app using webpack
AshwinCarvalho999/hello-rails-react pull request #1
Opened 2023-02-20 14:44 UTC by AshwinCarvalho999

## Creating a react-rails app using webpack
### In this PR, I completed the following tasks:
:ballot_box_with_check: Created a new rails app.
:ballot_box_with_check: Set it up with PostgreSQL, webpack and jsbundling-rails.
:ballot_box_with_check: Installed needed node dependencies.
:ballot_box_with_check: Created a babel.config.js file.
:ballot_box_with_check: Updated the webpack.config.js to include babel loader.
:ballot_box_with_check: Created a table for storing messages.
:ballot_box_with_check: Created an API endpoint to randomly select a greeting.
:ballot_box_with_check: Created a static view that will be the root of the app.
:ballot_box_with_check: Created an App component and render it in the static view.
:ballot_box_with_check: Created a Greeting component that displays a greeting.
:ballot_box_with_check: Created a redux-store to connect to the API endpoint
:ballot_box_with_check: Displayed the random greeting in the Greeting component.

2023-02-20 15:29 UTC, franclobo requested changes
Hi @AshwinCarvalho999, 

# ♻️ Required Changes ♻️

![so-close-jim-halpert](https://user-images.githubusercontent.com/58642949/220146676-d4c2cfc3-03fc-4753-8e48-aa20c4f1c205.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
- Gem `jsbundling-rails` is used 💯 
- Webpack is used 💯 
- React and redux are used ✔️ 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] When I run the command `./bin/dev` and open in `localhost:3000` the random greeting should appear but there were two links that returned **MESSAGE:** I recommend kindly using seeds to charge the random messages and showing them in the browser in the home page without links.

![image](https://user-images.githubusercontent.com/58642949/220145496-38b095ad-3201-4b4a-b4b7-c26c239d07f9.png)
![image](https://user-images.githubusercontent.com/58642949/220145556-dfc01117-1ab6-4155-9026-d92f8ba6c676.png)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-21 08:04 UTC, BenMukebo requested changes
Hi @AshwinCarvalho999, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To Highlight :clap: 
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️
- There is a `Greeting` component. ✔️



 ## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly make sure your app run correctly and display the random greeting in your Greeting component. As I have shown you in our zoom call you need to fix all the issue and make sure when you can run the local server correclty 👍🏻 

You have submitted a project, that Linters check are not running in the GitHub/action
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please Tag me on (@BenMukebo) when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-21 08:04 UTC, BenMukebo commented on app/javascript/application.js
> +  </Provider>,
- [ ] Great job so far, however, 🤔  I"ve noticed that you've removed the route to the Greeting component. Kindly bring it back. It will be great for the `App` component to have a route that leads to the `Greeting` component. This is a major requirement for this project to be approved. ⬇️ Kindly address this 

![Screenshot 2022-11-29 at 12 44 21](https://user-images.githubusercontent.com/32361963/204494979-44df610a-6db8-4bec-8b9d-4de721f7cde5.png)

2023-02-21 08:04 UTC, BenMukebo commented on config/routes.rb
> +end
- [ ] Great job so far 👏🏻 , however. You don't have to delete the main static route Kindly bring it back and make sure:
1. the created route is marked as `root`. :x: 
2. A controller with one action was created :x: 
3. A view for the root route is created (`root#index`) :x: 
   * It should include only `<div id="root">` The rest should be done with React and Redux. 😉

2023-02-21 08:04 UTC, BenMukebo commented on db/seeds.rb
> +#   Character.create(name: "Luke", movie: movies.first)
- [ ] Here is the project requirement 👇🏻Kindly Make you create 5 different greetings, for the table for storing your messages, Actually you can use the seed to create five different greetings. ✍🏻 

![image](https://user-images.githubusercontent.com/79058364/216478580-31fba987-8dbc-4d98-a4d2-c3194ab2609e.png)

2023-02-21 08:56 UTC, MahmoudBakr23 requested changes
Hi @AshwinCarvalho999 😃, 

## Highlights 💯

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

> Keep in mind that your long hours of work are appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it. 😄

 ## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

_Please see the comment under the review._

Cheers and Happy coding!👏👨‍💻💻

Feel free to mention @MahmoudBakr23 to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-21 08:56 UTC, MahmoudBakr23 commented on app/javascript/components/greeting.js
> +  console.log(greetings);
OPTIONAL
- Well done using `console.log` for debugging. However, kindly don't forget to remove it from the code before pushing changes. 🙏 It makes the code less clean and reduces the optimization of the app.

2023-02-21 08:56 UTC, MahmoudBakr23 commented on db/seeds.rb
> +#   Character.create(name: "Luke", movie: movies.first)
- [ ] The previous reviewer asked for this. Please use the seeds file to create 5 messages that will become their own randomly fetched messages by the front-end app. For example:
```ruby
Message.create(greetings: 'Message No.1')
Message.create(greetings: 'Message No.2')
Message.create(greetings: 'Message No.3')
Message.create(greetings: 'Message No.4')
Message.create(greetings: 'Message No.5')
```

2023-02-21 13:29 UTC, elisha2kyakpo1 approved these changes
Hi 👋 @AshwinCarvalho999, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

👍 You did a great job fixing the changes requested by the previous reviewers.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-21 13:59 UTC, merged